version: '3.1'

services:
  open-trace:
    container_name: example_cdi_trace
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
  db:
    container_name: example_cdi_db
    image: postgres
    restart: 'no'
    volumes:
      - example_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'example'
      POSTGRES_PASSWORD: 'eX4mpl3!'
      POSTGRES_DB: 'example'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
volumes:
  example_db: {}

